{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pokedex-api.serviceAccountName" . }}
  labels:
    {{- include "pokedex-api.labels" . | nindent 4 }}
  # {{- with .Values.serviceAccount.annotations }}
  annotations:
    iam.gke.io/gcp-service-account: "pkx-sa@technical-test-pgaona-16581.iam.gserviceaccount.com"
    # {{- toYaml . | nindent 4 }}
  # {{- end }}
{{- end }}
