kind: ConfigMap
apiVersion: v1
metadata:
#   namespace: {{ .Values.namespace }}
  name: {{ .Values.configmap.name }}
  annotations:
    # strategy.spinnaker.io/versioned: 'false'
data:
  config.json: |
    {
        "DATABASE_HOST":"pkx-api-mysql",
        "DATABASE_PORT":3306,
        "DATABASE_NAME":"minipokedex",
        "DATABASE_USER":"root",
        "DATABASE_PASSWORD":"password",
        "DATABASE_CHARSET":"utf8mb4",
        "REDIS_SCHEMA":"tcp",
        "REDIS_HOST":"pkx-api-redis-master",
        "REDIS_PORT":6379,
        "REDIS_AUTH":"secret",
        "MEMCACHED_HOST":"pkx-api-memcached",
        "MEMCACHED_PORT":11211
    }